dsp_to_database: root:password@tcp(localhost:3307)/iav2

logger:
  level: debug
  format: json
  output: /var/log/myapp.log
  prettyLog: true
  stacktrace: false
  outputPaths:
    - stderr


port: 8082

