dsp_to_database: root:password@tcp(localhost:3307)/iav2
service: redirect

logger:
  level: debug
  format: json
  output: /var/log/myapp.log
  prettyLog: true
  stacktrace: false
  outputPaths:
    - stdout


port: 8082
metricPort: 2112

